### ISSUE TITLE
Todo List 

### ISSUE THREAD

**Issue by pulkit-30** [ElixirTechCommunity/Elixir-website#3]
Todos: 

- [ ] Add basic UI(color) them.
- [ ] Create Navbar. 
- [ ] Add Hero Section.
- [ ] Add About Section(about all chapters under elixir).
- [ ] Add Team Section.
- [ ] Add Contact Form.
- [ ] Create Footer.

**Kindly, open an issue regarding each todo and post a comment before start working.**

**Comment by sam4rano** [comment]
I can contribute if you don't mind
